# -*- coding: utf-8 -*-

"""
googletranslateapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.configurations.global_configuration import GlobalConfiguration
from apimatic_core.decorators.lazy_property import LazyProperty
from googletranslateapi.configuration import Configuration
from googletranslateapi.controllers.base_controller import BaseController
from googletranslateapi.configuration import Environment
from googletranslateapi.http.auth.custom_header_authentication import CustomHeaderAuthentication
from googletranslateapi.controllers.test_controller import TestController


class GoogletranslateapiClient(object):

    @LazyProperty
    def test(self):
        return TestController(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION,
                 x_rapidapi_key='934533e5acmshf8fc49652f327f6p114b48jsn7b772d101303',
                 x_rapid_api_host='google-translate1.p.rapidapi.com',
                 content_type='x-www-form-urlencoded', config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         http_call_back=http_call_back,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment,
                                         x_rapidapi_key=x_rapidapi_key,
                                         x_rapid_api_host=x_rapid_api_host,
                                         content_type=content_type)
        else:
            self.config = config

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseController.user_agent(), BaseController.user_agent_parameters())
        self.initialize_auth_managers(self.global_configuration)

        self.global_configuration = self.global_configuration.auth_managers(self.auth_managers)

    def initialize_auth_managers(self, global_config):
        http_client_config = global_config.get_http_client_configuration()
        self.auth_managers = { key: None for key in ['global']}
        self.auth_managers['global'] = CustomHeaderAuthentication(http_client_config.x_rapidapi_key, http_client_config.x_rapid_api_host, http_client_config.content_type)
        return self.auth_managers
