# -*- coding: utf-8 -*-

"""
googletranslateapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class CustomHeaderAuthentication(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in CustomHeaderAuthentication

        """
        return "CustomHeaderAuthentication: X-Rapidapi-Key or X-RapidAPI-Host or Content-Type is undefined."

    def __init__(self, x_rapidapi_key, x_rapid_api_host, content_type):
        auth_params = {}
        if x_rapidapi_key:
            auth_params["X-Rapidapi-Key"] = x_rapidapi_key
        if x_rapid_api_host:
            auth_params["X-RapidAPI-Host"] = x_rapid_api_host
        if content_type:
            auth_params["Content-Type"] = content_type
        super().__init__(auth_params=auth_params)
        self._x_rapidapi_key = x_rapidapi_key
        self._x_rapid_api_host = x_rapid_api_host
        self._content_type = content_type
